apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: shared-storage
spec:
  containers:
  - name: container1
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /data
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-data-pvc
  # Add node affinity to ensure pods run on the same node
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - shared-storage
        topologyKey: "kubernetes.io/hostname"
