apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: shared-storage
spec:
  containers:
  - name: container2
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /data
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-data-pvc
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - shared-storage
        topologyKey: "kubernetes.io/hostname"
