apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: tanzu-storage-retain
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: test-volume2
  volumes:
    - name: test-volume2
      persistentVolumeClaim:
        claimName: test-pvc2
