apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trident-test-pvc
spec:
  accessModes:
    - ReadWriteMany # Allows multiple pods to access the volume
  resources:
    requests:
      storage: 5Gi
  storageClassName: trident-csi
